Repository teamulster2/report, pull requests merged in 2021-09, with the labels that each got.

#6 [issue/5] - Add ER diagramm for server side database
  ER_diragramm.drawio
  ER_diragramm.png
Labels: documentation

#9 [issue/5] - updated ER diagramm
  ER_diragramm
  ER_diragramm.drawio
  ER_diragramm.drawio.png
  ER_diragramm.png
Labels: documentation, enhancement

#11 [issue/10] - Added report setup
  diagrams/database/ER_diragramm
  diagrams/database/ER_diragramm.drawio.png
  diagrams/implementation/sq_user_client_server.drawio
  diagrams/implementation/sq_user_client_server.jpg
  report/00_abstract/00_abstract.md
  report/01_introduction/00_introduction.md
  report/02_background/00_background.md
  report/03_methodology/00_methodology.md
  report/03_methodology/01_project_management.md
  report/03_methodology/02_architecture.md
  report/03_methodology/03_database_management.md
  report/03_methodology/04_user_interface.md
  report/03_methodology/05_client_server_communication.md
  report/04_implementation/00_implementation.md
  report/04_implementation/01_flutter_application.md
  report/04_implementation/02_go_backend.md
  report/05_results_and_discussion/00_result_and_discussion.md
  report/06_conclusion/00_conclusion.md
  report/07_references/00_references.md
Labels: documentation

#13 Issue/12 UI part to report
  .gitignore
  diagrams/implementation/ui_1.png
  diagrams/implementation/ui_2.png
  diagrams/implementation/ui_3.png
  diagrams/implementation/ui_4.png
  report/00_abstract/00_abstract.md
  report/00_abstract/includes.yaml
  report/01_introduction/00_introduction.md
  report/01_introduction/includes.yaml
  report/02_background/00_background.md
  report/02_background/includes.yaml
  report/03_methodology/00_methodology.md
  report/03_methodology/01_project_management.md
  report/03_methodology/02_architecture.md
  report/03_methodology/03_database_management.md
  report/03_methodology/04_user_interface.md
  report/03_methodology/05_client_server_communication.md
  report/03_methodology/includes.yaml
  report/04_implementation/00_implementation.md
  report/04_implementation/01_flutter_application.md
  report/04_implementation/02_go_backend.md
  report/04_implementation/includes.yaml
  report/05_results_and_discussion/00_result_and_discussion.md
  report/05_results_and_discussion/includes.yaml
  report/06_conclusion/00_conclusion.md
  report/06_conclusion/includes.yaml
  report/07_references/00_references.md
  report/07_references/includes.yaml
  report/includes.yaml
  report/make.bat
Labels: documentation

#24 [issue/5] - Add notification time model
  diagrams/database/ER_diragramm
  diagrams/database/ER_diragramm.drawio.png
Labels: documentation, enhancement

#27 [issue/19] - Added conclusion content
  report/06_conclusion/00_conclusion.md
Labels: documentation

#29 [issue/16] - added notifications part
  report/04_implementation/01_flutter_application.md
Labels: enhancement

#30 [issue/17] - Add sections, [issue/20] - Add Makefile, [issue/20] - Add styles
  Makefile
  diagrams/implementation/service_provider_1.png
  diagrams/implementation/service_provider_2.png
  diagrams/implementation/service_provider_3.png
  make.bat
  report/00_abstract/includes.yaml
  report/01_introduction/includes.yaml
  report/02_background/includes.yaml
  report/03_methodology/02_architecture.md
  report/03_methodology/03_database_management.md
  report/03_methodology/04_user_interface.md
  report/03_methodology/includes.yaml
  report/04_implementation/01_flutter_application.md
  report/04_implementation/includes.yaml
  report/05_results_and_discussion/includes.yaml
  report/06_conclusion/includes.yaml
  report/07_references/includes.yaml
  report/includes.yaml
  report/make.bat
  report/report-build/disable_float.tex
  report/report-build/includes.yaml
  report/report-build/styles.md
Labels: documentation

#31 Issue/14 server
  report/03_methodology/05_client_server_communication.md
  report/04_implementation/02_go_backend.md
  report/04_implementation/02_go_server.md
  report/04_implementation/includes.yaml
Labels: documentation, enhancement

#33 Issue/28 server architektur
  report/03_methodology/02_architecture.md
Labels: documentation, enhancement

#34 Issue/32 formatting
  diagrams/background_06.png
  report/00_abstract/00_abstract.md
  report/01_introduction/00_introduction.md
  report/03_methodology/01_project_management.md
  report/03_methodology/02_architecture.md
  report/03_methodology/03_database_management.md
  report/04_implementation/01_flutter_application.md
  report/04_implementation/02_go_server.md
  report/07_references/00_references.md
Labels: documentation

#35 [issue/21,issue/3] - Write README and add toc
  README.md
  report/02_background/00_background.md
Labels: documentation, enhancement
